# Generated by Django 5.0.4 on 2024-04-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ("-is_done", "-created_at")},
        ),
        migrations.AddField(
            model_name="task",
            name="is_done",
            field=models.BooleanField(default=False),
        ),
    ]
