# Generated by Django 5.0.4 on 2024-04-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_alter_task_options_task_is_done"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="content",
            field=models.CharField(max_length=400),
        ),
    ]
